import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs"; // ✅ Import ClerkProvider
import "./globals.css";
import { ConvexClientProvider } from "@/providers/convex-client-provider";
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    //<ClerkProvider> {/* ✅ Wrap your layout */}
      <html lang="en">
        <body className={inter.className}>
          <ConvexClientProvider>
          {children}
          </ConvexClientProvider>
          
        </body>
      </html>
    //</ClerkProvider>
  );
}
